// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60d21SeR-EEX2EWh1IK67UVRbz4ssi1k',
    appId: '1:243951446428:web:8af5d279f3661a4b1b0059',
    messagingSenderId: '243951446428',
    projectId: 'practice-efdfd',
    authDomain: 'practice-efdfd.firebaseapp.com',
    storageBucket: 'practice-efdfd.firebasestorage.app',
    measurementId: 'G-HCY8W2PTPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU3AQnKeVXcmW2KtwBNCqqHHBk_xCO0sU',
    appId: '1:243951446428:android:79e7e77d47dc8fca1b0059',
    messagingSenderId: '243951446428',
    projectId: 'practice-efdfd',
    storageBucket: 'practice-efdfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjs9ZWVakhBRDb3-DXeolb_k7LzT2jb0o',
    appId: '1:243951446428:ios:f88a25a388bfbfd71b0059',
    messagingSenderId: '243951446428',
    projectId: 'practice-efdfd',
    storageBucket: 'practice-efdfd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
